version: "3.8"

services:
  db: &app
    build:
      context: .
        dockerfile: ./Dockerfile
    network_mode: host
    command: "./rinha-db-2024 5000"
    hostname: db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "125MB"
  api1:
    <<: *app
    command: "./rinha-backend-2024 3000 5000"
    hostname: api1
    depends_on:
      - db
    
  api2:
    <<: *app
    command: "./rinha-backend-2024 3001 5000"
    hostname: api2
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro      
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "175MB"
