version: "3.8"

services:
  base-app: &app
    build:
        context: .
        dockerfile: ./Dockerfile
    network_mode: host

  base-api: &api
    <<: *app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "125MB"
    depends_on:
      - db
  api1:
    <<: *api
    command: "./rinha-backend-2024 3000 5000"
    hostname: api1
    
  api2:
    <<: *api
    command: "./rinha-backend-2024 3001 5000"
    hostname: api2

  db:
    <<: *app
    command: "./rinha-db-2024 5000"
    hostname: db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro      
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "200MB"
